### ISSUE TITLE
会長「新しいことに挑戦しようとすることを忘れないようにして欲しい 」

### ISSUE THREAD

**Issue by zertatul0523** [Kiryu-kai/aphorism#3]
## 新しいことに挑戦しようとすることを忘れないようにして欲しい

「新しいことに挑戦しようとすることを忘れないようにして欲しい」

## アーカイブURL

<https://>youtu.be/XV-VghW7SaM

## 再生時間

00:00:00〜1:54:06

## 前向きな気持ち

結果の有無に関わらず新しい仕事に取り組み、常に挑戦する気持ちを忘れずに職務に関わりたいと思っています。

**Comment by zertatul0523** [comment]
> ## 新しいことに挑戦しようとすることを忘れないようにして欲しい
> 「新しいことに挑戦しようとすることを忘れないようにして欲しい」
> 
> ## アーカイブURL
> https://youtu.be/XV-VghW7SaM
> 
> ## 再生時間
> 00:00:00〜1:54:06
> 
> ## 格言の種類
> ## 前向きな気持ち
> 結果の有無に関わらず新しい仕事に取り組み、常に挑戦する気持ちを忘れずに職務に関わりたいと思っています。

**Comment by heppokofrontend** [comment]
@zertatul0523 さんリクエストありがとうございました！

<https://kiryu-kai.com/aphorism/XV-VghW7SaM.6830/>  
こちらで公開しました。また修正リクエストや追加リクエストがあれば、お気軽にIssueを立ててくださいね！🎉
