### ISSUE TITLE
会長「メモ帳を使って、パワポでも使ってろカス 」

### ISSUE THREAD

**Issue by arafat1815** [Kiryu-kai/aphorism#5]
## 格言全文

「せっかく色んな事ができるこんなソフトがあるのに、（多彩な機能を）何も使わせてもらえない。これならばメモ帳を使って、パワポでも使ってろカスという言葉でしょうか。」

## アーカイブURL

<https://youtu.be/hj9RVNXrzKo?t=541>

## 再生時間

00:09:01〜

## 格言の種類

かなココ　プロレス

## フリーエリア

Clip Studioをメモ帳代わりに使ったPP天使に対してクリスタの気持ちを代弁したもの

**Comment by heppokofrontend** [comment]
07/14 夜対応予定です👀

**Comment by heppokofrontend** [comment]
@arafat1815 リクエストありがとうございます！

お待たせしてすみません＞＜ 　
このようにしてみました。いかがでしょうか？👀

https://kiryu-kai.com/aphorism/hj9RVNXrzKo.514/

**Comment by arafat1815** [comment]
とてもいいと思います！
ありがとうございます！

2021年7月15日(木) 0:01 Ecma Kawarabe ***@***.***>:

**Comment by heppokofrontend** [comment]
よかったです！リクエストありがとうございました〜！🐉
