### ISSUE TITLE
会長「辛いけれど、大丈夫！夢は夢、持っていることが大切なんです。 」

### ISSUE THREAD

**Issue by tsuki719** [Kiryu-kai/aphorism#6]
## 格言全文

「辛いけれど、大丈夫！夢は夢、持っていることが大切なんです。」

## アーカイブURL

<https://youtu.be/0ngDDHw45AM>

## 再生時間

00:35:17〜

**Comment by heppokofrontend** [comment]
@tsuki719 https://kiryu-kai.com/aphorism/0ngDDHw45AM.2117/

追加しました！リクエストありがとうございました！
何かありましたらお気軽にコメントください～！🥒
